/* Generated By:JJTree: Do not edit this line. ASTANDExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTANDExpression extends SimpleNode {
  public ASTANDExpression(int id) {
    super(id);
  }

  public ASTANDExpression(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTANDExpression(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTANDExpression(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b2fb2f89af4b36ea6beb34dfdd5f7d55 (do not edit this line) */
