/* Generated By:JJTree: Do not edit this line. ASTDeclarationSpecifiers.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTDeclarationSpecifiers extends SimpleNode {
  public ASTDeclarationSpecifiers(int id) {
    super(id);
  }

  public ASTDeclarationSpecifiers(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTDeclarationSpecifiers(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTDeclarationSpecifiers(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c89b8b0f093eb2e5e9e40b9e48b3d3d3 (do not edit this line) */
