/* Generated By:JJTree: Do not edit this line. ASTDirectDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTDirectDeclarator extends SimpleNode {
  public ASTDirectDeclarator(int id) {
    super(id);
  }

  public ASTDirectDeclarator(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTDirectDeclarator(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTDirectDeclarator(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=313baa86971e109829899dddbaaf5a60 (do not edit this line) */
