/* Generated By:JJTree: Do not edit this line. ASTEnumeratorList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTEnumeratorList extends SimpleNode {
  public ASTEnumeratorList(int id) {
    super(id);
  }

  public ASTEnumeratorList(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTEnumeratorList(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTEnumeratorList(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a7d34e5e76b403848f60c3c9f06aab13 (do not edit this line) */
