/* Generated By:JJTree: Do not edit this line. ASTEnumerator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTEnumerator extends SimpleNode {
  public ASTEnumerator(int id) {
    super(id);
  }

  public ASTEnumerator(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTEnumerator(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTEnumerator(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=106278a76c21db8d1cec760d3bec5027 (do not edit this line) */
