/* Generated By:JJTree: Do not edit this line. ASTEnumSpecifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTEnumSpecifier extends SimpleNode {
  public ASTEnumSpecifier(int id) {
    super(id);
  }

  public ASTEnumSpecifier(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTEnumSpecifier(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTEnumSpecifier(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=23edfb249a6f4089500758eb7b59e161 (do not edit this line) */
