/* Generated By:JJTree: Do not edit this line. ASTExclusiveORExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTExclusiveORExpression extends SimpleNode {
  public ASTExclusiveORExpression(int id) {
    super(id);
  }

  public ASTExclusiveORExpression(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTExclusiveORExpression(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTExclusiveORExpression(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=79d6bbaf5dae3d0dcbb86e0c05b5db37 (do not edit this line) */
