/* Generated By:JJTree: Do not edit this line. ASTFunctionModelComment.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTFunctionModelComment extends SimpleNode {
  public ASTFunctionModelComment(int id) {
    super(id);
  }

  public ASTFunctionModelComment(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTFunctionModelComment(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTFunctionModelComment(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5ff0c0e420638a6415f8b9d203a4b4ed (do not edit this line) */
