/* Generated By:JJTree: Do not edit this line. ASTFunctionInitDeclaratorList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTFunctionInitDeclaratorList extends SimpleNode {
  public ASTFunctionInitDeclaratorList(int id) {
    super(id);
  }

  public ASTFunctionInitDeclaratorList(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTFunctionInitDeclaratorList(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTFunctionInitDeclaratorList(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f0ae1de76e2d8ff109fbdd6174f8b742 (do not edit this line) */
