/* Generated By:JJTree: Do not edit this line. ASTFunctionDeclarationList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTFunctionDeclarationList extends SimpleNode {
  public ASTFunctionDeclarationList(int id) {
    super(id);
  }

  public ASTFunctionDeclarationList(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTFunctionDeclarationList(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTFunctionDeclarationList(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6ac217899c2f2757c413ed5428e20d41 (do not edit this line) */
