/* Generated By:JJTree: Do not edit this line. ASTFunctionDefinition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTFunctionDefinition extends SimpleNode {
  public ASTFunctionDefinition(int id) {
    super(id);
  }

  public ASTFunctionDefinition(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTFunctionDefinition(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTFunctionDefinition(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=86e58ae03fdb73b1595c38e01371fad0 (do not edit this line) */
