/* Generated By:JJTree: Do not edit this line. ASTFunctionDirectDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTFunctionDirectDeclarator extends SimpleNode {
  public ASTFunctionDirectDeclarator(int id) {
    super(id);
  }

  public ASTFunctionDirectDeclarator(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTFunctionDirectDeclarator(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTFunctionDirectDeclarator(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cc1fa826ecef1e76cc29ee25a8035834 (do not edit this line) */
