/* Generated By:JJTree: Do not edit this line. ASTFunctionModelDefinition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTFunctionModelDefinition extends SimpleNode {
  public ASTFunctionModelDefinition(int id) {
    super(id);
  }

  public ASTFunctionModelDefinition(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTFunctionModelDefinition(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTFunctionModelDefinition(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=420e091cae0bb4b35cd0a6a792e315f1 (do not edit this line) */
