/* Generated By:JJTree: Do not edit this line. ASTFunctionInitDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTFunctionInitDeclarator extends SimpleNode {
  public ASTFunctionInitDeclarator(int id) {
    super(id);
  }

  public ASTFunctionInitDeclarator(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTFunctionInitDeclarator(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTFunctionInitDeclarator(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=198d4c5934672f5a2c3bc5712cf8e874 (do not edit this line) */
