/* Generated By:JJTree: Do not edit this line. ASTFunctionDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTFunctionDeclaration extends SimpleNode {
  public ASTFunctionDeclaration(int id) {
    super(id);
  }

  public ASTFunctionDeclaration(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTFunctionDeclaration(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTFunctionDeclaration(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2fa5bdf74ec2f187351310f726d26ba7 (do not edit this line) */
