/* Generated By:JJTree: Do not edit this line. ASTFunctionPointerDirectDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTFunctionPointerDirectDeclarator extends SimpleNode {
  public ASTFunctionPointerDirectDeclarator(int id) {
    super(id);
  }

  public ASTFunctionPointerDirectDeclarator(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTFunctionPointerDirectDeclarator(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTFunctionPointerDirectDeclarator(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6f468907e0ea22c4da3c63b21baa0e35 (do not edit this line) */
