/* Generated By:JJTree: Do not edit this line. ASTFlowModelDefinition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTFlowModelDefinition extends SimpleNode {
  public ASTFlowModelDefinition(int id) {
    super(id);
  }

  public ASTFlowModelDefinition(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTFlowModelDefinition(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTFlowModelDefinition(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=326bd87bbd012737b20fa7431d683b71 (do not edit this line) */
