/* Generated By:JJTree: Do not edit this line. ASTInitDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTInitDeclarator extends SimpleNode {
  public ASTInitDeclarator(int id) {
    super(id);
  }

  public ASTInitDeclarator(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTInitDeclarator(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTInitDeclarator(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=904eb7329905f1d6769c67f13c331335 (do not edit this line) */
