/* Generated By:JJTree: Do not edit this line. ASTInclusiveORExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTInclusiveORExpression extends SimpleNode {
  public ASTInclusiveORExpression(int id) {
    super(id);
  }

  public ASTInclusiveORExpression(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTInclusiveORExpression(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTInclusiveORExpression(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=48e940069cd48a36907e8509987d9fda (do not edit this line) */
