/* Generated By:JJTree: Do not edit this line. ASTInitializerList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTInitializerList extends SimpleNode {
  public ASTInitializerList(int id) {
    super(id);
  }

  public ASTInitializerList(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTInitializerList(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTInitializerList(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e737c15e9d78fe0a4771a5605172ed0f (do not edit this line) */
