/* Generated By:JJTree: Do not edit this line. ASTIdentifierList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTIdentifierList extends SimpleNode {
  public ASTIdentifierList(int id) {
    super(id);
  }

  public ASTIdentifierList(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTIdentifierList(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTIdentifierList(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a738734af90a5005844cd13655851746 (do not edit this line) */
