/* Generated By:JJTree: Do not edit this line. ASTLogicalANDExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTLogicalANDExpression extends SimpleNode {
  public ASTLogicalANDExpression(int id) {
    super(id);
  }

  public ASTLogicalANDExpression(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTLogicalANDExpression(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTLogicalANDExpression(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=07171b974c6400ab72086b130df3d9a0 (do not edit this line) */
