/* Generated By:JJTree: Do not edit this line. ASTLogicalORExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTLogicalORExpression extends SimpleNode {
  public ASTLogicalORExpression(int id) {
    super(id);
  }

  public ASTLogicalORExpression(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTLogicalORExpression(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTLogicalORExpression(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=61b7720311d5e2f33161df60606da69f (do not edit this line) */
