/* Generated By:JJTree: Do not edit this line. ASTMultiSpecifierQualifierList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTMultiSpecifierQualifierList extends SimpleNode {
  public ASTMultiSpecifierQualifierList(int id) {
    super(id);
  }

  public ASTMultiSpecifierQualifierList(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTMultiSpecifierQualifierList(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTMultiSpecifierQualifierList(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=017da8b671cae7ce9f4c82606ca63144 (do not edit this line) */
