/* Generated By:JJTree: Do not edit this line. ASTParameterDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTParameterDeclarator extends SimpleNode {
  public ASTParameterDeclarator(int id) {
    super(id);
  }

  public ASTParameterDeclarator(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTParameterDeclarator(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTParameterDeclarator(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=684f829594ba5bd057912d65a08aa1dc (do not edit this line) */
