/* Generated By:JJTree: Do not edit this line. ASTPointer.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTPointer extends SimpleNode {
  public ASTPointer(int id) {
    super(id);
  }

  public ASTPointer(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTPointer(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTPointer(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0c2bb21f48820c82b0aac1a3ce96a3e1 (do not edit this line) */
