/* Generated By:JJTree: Do not edit this line. ASTParameterTypeList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTParameterTypeList extends SimpleNode {
  public ASTParameterTypeList(int id) {
    super(id);
  }

  public ASTParameterTypeList(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTParameterTypeList(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTParameterTypeList(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=833815ffda91ab34cda43e43cff73040 (do not edit this line) */
