/* Generated By:JJTree: Do not edit this line. ASTStructDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTStructDeclaration extends SimpleNode {
  public ASTStructDeclaration(int id) {
    super(id);
  }

  public ASTStructDeclaration(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTStructDeclaration(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTStructDeclaration(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=473ec182bfaaf1e19a90d39a3ef9eb9f (do not edit this line) */
