/* Generated By:JJTree: Do not edit this line. ASTStructDeclarationList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTStructDeclarationList extends SimpleNode {
  public ASTStructDeclarationList(int id) {
    super(id);
  }

  public ASTStructDeclarationList(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTStructDeclarationList(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTStructDeclarationList(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c5574ef84162d17d181a3375c593e00a (do not edit this line) */
