/* Generated By:JJTree: Do not edit this line. ASTStructDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTStructDeclarator extends SimpleNode {
  public ASTStructDeclarator(int id) {
    super(id);
  }

  public ASTStructDeclarator(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTStructDeclarator(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTStructDeclarator(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5f7af25e28dba1ba4bf6f765c8647ad3 (do not edit this line) */
