/* Generated By:JJTree: Do not edit this line. ASTStructOrUnionSpecifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTStructOrUnionSpecifier extends SimpleNode {
  public ASTStructOrUnionSpecifier(int id) {
    super(id);
  }

  public ASTStructOrUnionSpecifier(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTStructOrUnionSpecifier(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTStructOrUnionSpecifier(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6c6d2381cf4313c7f8f1ed54a263b9e8 (do not edit this line) */
