/* Generated By:JJTree: Do not edit this line. ASTStorageClassSpecifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTStorageClassSpecifier extends SimpleNode {
  public ASTStorageClassSpecifier(int id) {
    super(id);
  }

  public ASTStorageClassSpecifier(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTStorageClassSpecifier(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTStorageClassSpecifier(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fa53fed4c75a315911f3e674d7f5a817 (do not edit this line) */
