/* Generated By:JJTree: Do not edit this line. ASTStructDeclaratorList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTStructDeclaratorList extends SimpleNode {
  public ASTStructDeclaratorList(int id) {
    super(id);
  }

  public ASTStructDeclaratorList(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTStructDeclaratorList(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTStructDeclaratorList(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=524d45509a4e61d616b24219eee5ee6e (do not edit this line) */
