/* Generated By:JJTree: Do not edit this line. ASTTypeQualifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTTypeQualifier extends SimpleNode {
  public ASTTypeQualifier(int id) {
    super(id);
  }

  public ASTTypeQualifier(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTTypeQualifier(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTTypeQualifier(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=78349ee98706d2069521e352e0702c8b (do not edit this line) */
