/* Generated By:JJTree: Do not edit this line. ASTTypeQualifierList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTTypeQualifierList extends SimpleNode {
  public ASTTypeQualifierList(int id) {
    super(id);
  }

  public ASTTypeQualifierList(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTTypeQualifierList(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTTypeQualifierList(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a37f4b3daf7da1e72bf551089d4e0af2 (do not edit this line) */
