/* Generated By:JJTree: Do not edit this line. ASTTypedefName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTTypedefName extends SimpleNode {
  public ASTTypedefName(int id) {
    super(id);
  }

  public ASTTypedefName(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTTypedefName(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTTypedefName(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6d0370953a6bed3ab926f079fddbfbfc (do not edit this line) */
