/* Generated By:JJTree: Do not edit this line. ASTTypeName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTTypeName extends SimpleNode {
  public ASTTypeName(int id) {
    super(id);
  }

  public ASTTypeName(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTTypeName(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTTypeName(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7b814f2f889adce76d904b768320b1bf (do not edit this line) */
