/* Generated By:JJTree: Do not edit this line. ASTTypeSpecifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTTypeSpecifier extends SimpleNode {
  public ASTTypeSpecifier(int id) {
    super(id);
  }

  public ASTTypeSpecifier(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTTypeSpecifier(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTTypeSpecifier(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b6e9314990041de5f12657da0f6af874 (do not edit this line) */
