/* Generated By:JJTree: Do not edit this line. ASTUnaryOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTUnaryOperator extends SimpleNode {
  public ASTUnaryOperator(int id) {
    super(id);
  }

  public ASTUnaryOperator(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTUnaryOperator(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTUnaryOperator(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f821795415fcee591a31e52326dc9e84 (do not edit this line) */
