/* Generated By:JJTree: Do not edit this line. ASTVariableModelDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTVariableModelDeclaration extends SimpleNode {
  public ASTVariableModelDeclaration(int id) {
    super(id);
  }

  public ASTVariableModelDeclaration(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTVariableModelDeclaration(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTVariableModelDeclaration(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=495b02cd699a584976559357669cb554 (do not edit this line) */
