/* Generated By:JJTree: Do not edit this line. ASTVariableDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTVariableDeclaration extends SimpleNode {
  public ASTVariableDeclaration(int id) {
    super(id);
  }

  public ASTVariableDeclaration(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTVariableDeclaration(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTVariableDeclaration(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9cf2b781ea13849c72f5cdbcbfb23aa3 (do not edit this line) */
