/* Generated By:JJTree: Do not edit this line. ASTVariableInitDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTVariableInitDeclarator extends SimpleNode {
  public ASTVariableInitDeclarator(int id) {
    super(id);
  }

  public ASTVariableInitDeclarator(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTVariableInitDeclarator(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTVariableInitDeclarator(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8844b4ea35e5171907160fe0e06ff134 (do not edit this line) */
