/* Generated By:JJTree: Do not edit this line. ASTVariableDirectDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTVariableDirectDeclarator extends SimpleNode {
  public ASTVariableDirectDeclarator(int id) {
    super(id);
  }

  public ASTVariableDirectDeclarator(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTVariableDirectDeclarator(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTVariableDirectDeclarator(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2bae7dbbc565756833cff5a3cbfa0c30 (do not edit this line) */
