/* Generated By:JJTree: Do not edit this line. ASTVariableInitDeclaratorList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.textmodel.ast;

public
class ASTVariableInitDeclaratorList extends SimpleNode {
  public ASTVariableInitDeclaratorList(int id) {
    super(id);
  }

  public ASTVariableInitDeclaratorList(TMParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTVariableInitDeclaratorList(id);
  }

  public static Node jjtCreate(TMParser p, int id) {
    return new ASTVariableInitDeclaratorList(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(TMParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d278e8c72f20f961cc4137c060d6121f (do not edit this line) */
